### ISSUE TITLE
zope-compose-haproxy-1 doesn't start up

### ISSUE THREAD

**Issue by tytytytyy** [gandie/interfaces-docker#2]
**Describe the bug**
zope-compose-haproxy-1 cant be build till the end. 

**To Reproduce**
1. Followed the read me Instructions
2. When tryin to build with ./StartZopeCompose Error message occurs added below

**Expected behavior**

The Package doesn't compose properly because zope-compose-haproxy-1 doesn't start up hence Website cant be started.

**Error Message**

zope-compose-haproxy-1       | [NOTICE]   (9) : haproxy version is 2.4.22-0ubuntu0.22.04.1
zope-compose-haproxy-1       | [NOTICE]   (9) : path to executable is /usr/sbin/haproxy
zope-compose-haproxy-1       | [ALERT]    (9) : parsing [/etc/haproxy/haproxy.cfg:35] : 'server zope1' : could not resolve address 'zope-compose_zope_1'.
zope-compose-haproxy-1       | [ALERT]    (9) : parsing [/etc/haproxy/haproxy.cfg:36] : 'server zope2' : could not resolve address 'zope-compose_zope_2'.
zope-compose-haproxy-1       | [ALERT]    (9) : parsing [/etc/haproxy/haproxy.cfg:37] : 'server zope3' : could not resolve address 'zope-compose_zope_3'.

**Comment by gandie** [comment]
Heyho! Thx for the detailed issue description! I guess i know where the problem might be, will keep u posted

**Comment by gandie** [comment]
Just tried to reproduce the error ... but no success. Installation worked fine on fresh Ubuntu22-server.

The error seems like something went wrong firing up the zope instances causing haproxy to fail. Sometimes there seems to be a tminig problem in the startup process.

Thing to try:
- Reboot the system / restart containers, get around the timing issue maybe?
- Is there more output regarding the error? I'd love to know _why_ zope can't start, there should be more errors firing before the one u've posted
