### ISSUE TITLE
error starting the instruction ./StartZopeCompose

### ISSUE THREAD

**Issue by paolopastorino** [gandie/interfaces-docker#3]
Hi, i get the following error on macbook pro m1 with macOs 12.1:
5.839 ERROR: Could not find a version that satisfies the requirement mediapipe==0.9.1.0 (from versions: 0.10.3)
5.839 ERROR: No matching distribution found for mediapipe==0.9.1.0
------
failed to solve: process "/bin/sh -c pip3 install zope     psycopg2-binary     git+https://github.com/gandie/Products.PythonScripts@hacked-python-scripts     Products.ZSQLMethods     Products.SiteErrorLog     Products.StandardCacheManagers     Products.ExternalMethod     Products.MailHost     git+https://github.com/perfact/ZPsycopgDA     git+https://loc.kplays.de:8080/Python/dockerutils.git     zope.mkzeoinstance     Paste     jsonpath-ng     mediapipe==0.9.1.0" did not complete successfully: exit code: 1

**Comment by gandie** [comment]
Hi!
We encountered this issue a while ago, but i had no chance to reproduce the error which is weird. I've just preapred a laptop with an installation which went just fine ( on Ubuntu 20.04 host system ). One thing i also checked was installing mediapipe separately to check for its availability.

Can u try to install mediapipe into a separate virtual environment for testing?
